/**
 * {@summary Writes messages to the system logs. The value returned by the function is the last argument passed.}
 * Logging functions, in order of priority from highest to lowest, are:
 * <ul>
 *   <li>log.error(first, others...)</li>
 *   <li>log.warn(first, others...)</li>
 *   <li>log.info(first, others...)</li>
 *   <li>log.debug(first, others...)</li>
 *   <li>log.trace(first, others...)</li>
 * </ul>
 * At least one argument must be passed to the logging function.
 * <p>
 * Logging can be used by the client to debug problematic expressions or monitor values generated by
 * an expression.
 * <p>
 * <b>Examples</b>
 * <ol>
 *   <li>
 *      Given:
 *      <pre>    $log.debug(1 + 2 + 3)</pre>
 *      calculates {@literal 6}, logs it at debug level, and returns it as
 *      {@link com.github.tymefly.eel.Type#NUMBER} to the client application.
 *   </li>
 *   <li>
 *      As logging hardcoded values is rarely useful; however, EEL can log values read from the SymbolsTable.
 *      <pre>    Hello: $log.info(${userName})</pre>
 *      will read a value from the SymbolsTable, log it, and use it as part of a friendly message.
 *   </li>
 *   <li>
 *      Given:
 *      <pre>    The Result is: ${key-$log.info("defaulting to {}", "defaultValue")}</pre>
 *      If {@literal key} exists in the SymbolsTable, its value is returned without logging. If the value
 *      cannot be read, a warning is logged and {@literal defaultValue} is returned. This works because a
 *      variable's default value is an EEL expression and can contain embedded function calls.
 *   </li>
 * </ol>
 * <b>Notes:</b>
 * <ol>
 *   <li>The client's logging framework is responsible for enabling logging.</li>
 *   <li>All messages are written to the <b>{@value com.github.tymefly.eel.function.log.EelLogger#EEL_LOGGER}</b>
 *      logger, which should be configured with <b>trace</b> level logging enabled.</li>
 *   <li>To prevent log repudiation attacks:
 *     <ul>
 *       <li>All logged messages are prefixed with the literal text {@code Logged EEL Message:} to indicate
 *           they are generated by EEL. This prefix cannot be changed or removed.</li>
 *       <li>Only printable characters and tabs are logged. Control characters, including new lines and
 *           Unicode characters outside the printable range, are silently filtered out.</li>
 *     </ul>
 *   </li>
 * </ol>
 */
@GroupDescription("log")
package com.github.tymefly.eel.function.log;

import com.github.tymefly.eel.udf.GroupDescription;